name: Portfolio
author: Bhaskar Kishor
title: Portfolio 
description:
  site: A portfolio website
  about: A Engineering Undergrad with a degree in Mechanical Engineering from one of the IITs, pursuing my interest in other domains, Web Development and Software development.
  birthday: 23 January, 2000
  address: 
    desc: Patna, Bihar, India
    zipcode: 800020
email: bk20@iitbbs.ac.in
phone: 9472256831
website: bhaskarkishor.github.io
image:
  me: images/me.jpg

livereload: true

